theorem mul_left_cancel (a b c : mynat) (ha : a ≠ 0) : a * b = a * c → b = c :=
begin
induction c with d hd generalizing b,
rw mul_zero,
intro h,
cases (eq_zero_or_eq_zero_of_mul_eq_zero _ _ h) with h1 h2,
exfalso,
apply ha,
exact h1,
exact h2,
intro hb,
cases b,
rw mul_zero at hb,
exfalso,
apply ha,
symmetry at hb,
cases (eq_zero_or_eq_zero_of_mul_eq_zero _ _ hb) with h1 h2,
exact h1,
exfalso,
exact succ_ne_zero _ h2,
have h : b = d,
apply hd,
rw mul_succ at hb,
rw mul_succ at hb,
exact add_right_cancel _ _ _ hb,
rwa h,
end
